import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Background from "@/app/ui/background";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next TODOs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background />
        <div className="min-h-screen relative">
          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 shadow-2xl bg-gray-50 rounded-xl w-1/4 h-2/4 z-10">
            {/* <TaskList /> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
